import {
  filterRepositories,
  sortRepositories,
  type Repository,
  type RepositorySort,
} from "@/lib/repositories";

export const mockRepositories: Repository[] = [
  {
    id: 1,
    owner: "astral-sh",
    name: "uv",
    fullName: "astral-sh/uv",
    description: "An extremely fast Python package and project manager written in Rust.",
    stars: 68340,
    forks: 1940,
    openIssues: 912,
    watchers: 410,
    language: "Rust",
    license: "Apache-2.0",
    topics: ["python", "package-manager", "developer-tools", "rust"],
    createdAt: "2023-10-05T00:00:00Z",
    updatedAt: "2026-08-23T18:10:00Z",
    pushedAt: "2026-08-23T17:40:00Z",
    starDelta7d: 1240,
    contributorCount: 486,
    isVerified: true,
    homepage: "https://docs.astral.sh/uv/",
    htmlUrl: "https://github.com/astral-sh/uv",
    avatarUrl: "https://github.com/astral-sh.png",
  },
  {
    id: 2,
    owner: "sxyazi",
    name: "yazi",
    fullName: "sxyazi/yazi",
    description: "A terminal file manager with async I/O and image preview support.",
    stars: 31220,
    forks: 760,
    openIssues: 287,
    watchers: 214,
    language: "Rust",
    license: "MIT",
    topics: ["terminal", "file-manager", "linux", "developer-tools"],
    createdAt: "2023-05-19T00:00:00Z",
    updatedAt: "2026-08-23T16:08:00Z",
    pushedAt: "2026-08-23T14:21:00Z",
    starDelta7d: 684,
    contributorCount: 231,
    isVerified: false,
    htmlUrl: "https://github.com/sxyazi/yazi",
    avatarUrl: "https://github.com/sxyazi.png",
  },
  {
    id: 3,
    owner: "atuinsh",
    name: "atuin",
    fullName: "atuinsh/atuin",
    description: "Magical shell history with sync, search, and private encrypted storage.",
    stars: 27860,
    forks: 740,
    openIssues: 336,
    watchers: 180,
    language: "Rust",
    license: "MIT",
    topics: ["shell", "terminal", "linux", "productivity"],
    createdAt: "2021-04-15T00:00:00Z",
    updatedAt: "2026-08-22T20:14:00Z",
    pushedAt: "2026-08-22T18:40:00Z",
    starDelta7d: 415,
    contributorCount: 272,
    isVerified: false,
    homepage: "https://atuin.sh",
    htmlUrl: "https://github.com/atuinsh/atuin",
    avatarUrl: "https://github.com/atuinsh.png",
  },
  {
    id: 4,
    owner: "ghostty-org",
    name: "ghostty",
    fullName: "ghostty-org/ghostty",
    description: "A fast, feature-rich, cross-platform terminal emulator using native UI.",
    stars: 44210,
    forks: 1580,
    openIssues: 864,
    watchers: 320,
    language: "Zig",
    license: "MIT",
    topics: ["terminal", "zig", "macos", "linux"],
    createdAt: "2024-03-09T00:00:00Z",
    updatedAt: "2026-08-23T19:30:00Z",
    pushedAt: "2026-08-23T19:12:00Z",
    starDelta7d: 932,
    contributorCount: 512,
    isVerified: true,
    homepage: "https://ghostty.org",
    htmlUrl: "https://github.com/ghostty-org/ghostty",
    avatarUrl: "https://github.com/ghostty-org.png",
  },
  {
    id: 5,
    owner: "cachix",
    name: "devenv",
    fullName: "cachix/devenv",
    description: "Fast, declarative, reproducible developer environments powered by Nix.",
    stars: 6150,
    forks: 420,
    openIssues: 348,
    watchers: 92,
    language: "Nix",
    license: "Apache-2.0",
    topics: ["nix", "developer-tools", "dev-environment", "linux"],
    createdAt: "2021-11-18T00:00:00Z",
    updatedAt: "2026-08-23T18:20:00Z",
    pushedAt: "2026-08-23T17:02:00Z",
    starDelta7d: 188,
    contributorCount: 246,
    isVerified: false,
    homepage: "https://devenv.sh",
    htmlUrl: "https://github.com/cachix/devenv",
    avatarUrl: "https://github.com/cachix.png",
  },
  {
    id: 6,
    owner: "tracel-ai",
    name: "burn",
    fullName: "tracel-ai/burn",
    description: "A flexible deep learning framework built in Rust with multiple backends.",
    stars: 12840,
    forks: 670,
    openIssues: 238,
    watchers: 122,
    language: "Rust",
    license: "Apache-2.0",
    topics: ["machine-learning", "rust", "gpu", "deep-learning"],
    createdAt: "2022-06-20T00:00:00Z",
    updatedAt: "2026-08-23T15:40:00Z",
    pushedAt: "2026-08-23T12:30:00Z",
    starDelta7d: 356,
    contributorCount: 194,
    isVerified: false,
    homepage: "https://burn.dev",
    htmlUrl: "https://github.com/tracel-ai/burn",
    avatarUrl: "https://github.com/tracel-ai.png",
  },
  {
    id: 7,
    owner: "immich-app",
    name: "immich",
    fullName: "immich-app/immich",
    description: "A high performance self-hosted photo and video management solution.",
    stars: 78200,
    forks: 4120,
    openIssues: 420,
    watchers: 590,
    language: "TypeScript",
    license: "AGPL-3.0",
    topics: ["self-hosted", "photos", "docker", "typescript"],
    createdAt: "2022-02-03T00:00:00Z",
    updatedAt: "2026-08-23T19:42:00Z",
    pushedAt: "2026-08-23T19:35:00Z",
    starDelta7d: 1460,
    contributorCount: 871,
    isVerified: true,
    homepage: "https://immich.app",
    htmlUrl: "https://github.com/immich-app/immich",
    avatarUrl: "https://github.com/immich-app.png",
  },
  {
    id: 8,
    owner: "spacedriveapp",
    name: "spacedrive",
    fullName: "spacedriveapp/spacedrive",
    description: "An open source cross-platform file explorer powered by a virtual distributed filesystem.",
    stars: 37260,
    forks: 1240,
    openIssues: 305,
    watchers: 301,
    language: "Rust",
    license: "AGPL-3.0",
    topics: ["file-manager", "desktop", "rust", "self-hosted"],
    createdAt: "2021-10-09T00:00:00Z",
    updatedAt: "2026-08-21T14:32:00Z",
    pushedAt: "2026-08-21T10:20:00Z",
    starDelta7d: 203,
    contributorCount: 382,
    isVerified: false,
    homepage: "https://spacedrive.com",
    htmlUrl: "https://github.com/spacedriveapp/spacedrive",
    avatarUrl: "https://github.com/spacedriveapp.png",
  },
  {
    id: 9,
    owner: "openbao",
    name: "openbao",
    fullName: "openbao/openbao",
    description: "An open source, community-driven fork for secrets and identity management.",
    stars: 4820,
    forks: 380,
    openIssues: 214,
    watchers: 78,
    language: "Go",
    license: "MPL-2.0",
    topics: ["security", "secrets", "devops", "go"],
    createdAt: "2023-12-12T00:00:00Z",
    updatedAt: "2026-08-23T12:45:00Z",
    pushedAt: "2026-08-23T11:53:00Z",
    starDelta7d: 224,
    contributorCount: 164,
    isVerified: false,
    homepage: "https://openbao.org",
    htmlUrl: "https://github.com/openbao/openbao",
    avatarUrl: "https://github.com/openbao.png",
  },
  {
    id: 10,
    owner: "pop-os",
    name: "cosmic-epoch",
    fullName: "pop-os/cosmic-epoch",
    description: "The next generation COSMIC desktop environment for Linux, written in Rust.",
    stars: 6707,
    forks: 207,
    openIssues: 1791,
    watchers: 94,
    language: "Just",
    license: "Not specified",
    topics: ["linux", "desktop-environment", "rust", "wayland"],
    createdAt: "2022-04-12T18:36:39Z",
    updatedAt: "2026-08-24T15:43:34Z",
    pushedAt: "2026-08-20T01:01:45Z",
    starDelta7d: 292,
    contributorCount: 283,
    isVerified: true,
    homepage: "https://system76.com/cosmic",
    htmlUrl: "https://github.com/pop-os/cosmic-epoch",
    avatarUrl: "https://github.com/pop-os.png",
  },
  {
    id: 11,
    owner: "ethereum-optimism",
    name: "optimism",
    fullName: "ethereum-optimism/optimism",
    description: "The Optimism monorepo containing the OP Stack and related infrastructure.",
    stars: 6120,
    forks: 3180,
    openIssues: 492,
    watchers: 260,
    language: "Go",
    license: "MIT",
    topics: ["defi", "ethereum", "layer-2", "blockchain"],
    createdAt: "2019-10-04T00:00:00Z",
    updatedAt: "2026-08-23T19:44:00Z",
    pushedAt: "2026-08-23T19:41:00Z",
    starDelta7d: 82,
    contributorCount: 763,
    isVerified: true,
    homepage: "https://optimism.io",
    htmlUrl: "https://github.com/ethereum-optimism/optimism",
    avatarUrl: "https://github.com/ethereum-optimism.png",
  },
  {
    id: 12,
    owner: "paradigmxyz",
    name: "reth",
    fullName: "paradigmxyz/reth",
    description: "A modular, contributor-friendly and blazing-fast Ethereum execution client.",
    stars: 6850,
    forks: 1540,
    openIssues: 520,
    watchers: 151,
    language: "Rust",
    license: "Apache-2.0",
    topics: ["defi", "ethereum", "blockchain", "rust"],
    createdAt: "2022-05-18T00:00:00Z",
    updatedAt: "2026-08-23T19:22:00Z",
    pushedAt: "2026-08-23T18:50:00Z",
    starDelta7d: 174,
    contributorCount: 581,
    isVerified: true,
    homepage: "https://reth.rs",
    htmlUrl: "https://github.com/paradigmxyz/reth",
    avatarUrl: "https://github.com/paradigmxyz.png",
  },
  {
    id: 13,
    owner: "flxzt",
    name: "rnote",
    fullName: "flxzt/rnote",
    description: "A sketch and handwritten note-taking application for Linux and macOS.",
    stars: 9850,
    forks: 420,
    openIssues: 271,
    watchers: 94,
    language: "Rust",
    license: "GPL-3.0",
    topics: ["linux", "drawing", "notes", "gtk"],
    createdAt: "2021-08-14T00:00:00Z",
    updatedAt: "2026-08-22T17:30:00Z",
    pushedAt: "2026-08-22T16:42:00Z",
    starDelta7d: 271,
    contributorCount: 103,
    isVerified: false,
    homepage: "https://rnote.flxzt.net",
    htmlUrl: "https://github.com/flxzt/rnote",
    avatarUrl: "https://github.com/flxzt.png",
  },
  {
    id: 14,
    owner: "jesseduffield",
    name: "lazygit",
    fullName: "jesseduffield/lazygit",
    description: "A simple terminal UI for git commands with an efficient keyboard workflow.",
    stars: 65420,
    forks: 2380,
    openIssues: 366,
    watchers: 520,
    language: "Go",
    license: "MIT",
    topics: ["git", "terminal", "developer-tools", "go"],
    createdAt: "2018-01-02T00:00:00Z",
    updatedAt: "2026-08-23T11:18:00Z",
    pushedAt: "2026-08-23T09:14:00Z",
    starDelta7d: 610,
    contributorCount: 650,
    isVerified: true,
    htmlUrl: "https://github.com/jesseduffield/lazygit",
    avatarUrl: "https://github.com/jesseduffield.png",
  },
  {
    id: 15,
    owner: "plasma-umass",
    name: "scalene",
    fullName: "plasma-umass/scalene",
    description: "A high-performance CPU, GPU, and memory profiler for Python.",
    stars: 12360,
    forks: 530,
    openIssues: 102,
    watchers: 111,
    language: "Python",
    license: "Apache-2.0",
    topics: ["python", "profiler", "performance", "developer-tools"],
    createdAt: "2020-04-10T00:00:00Z",
    updatedAt: "2026-08-20T13:35:00Z",
    pushedAt: "2026-08-20T12:28:00Z",
    starDelta7d: 146,
    contributorCount: 94,
    isVerified: false,
    homepage: "https://plasma-umass.org/scalene/",
    htmlUrl: "https://github.com/plasma-umass/scalene",
    avatarUrl: "https://github.com/plasma-umass.png",
  },
  {
    id: 16,
    owner: "mullvad",
    name: "mullvadvpn-app",
    fullName: "mullvad/mullvadvpn-app",
    description: "The privacy-focused Mullvad VPN client for desktop and mobile platforms.",
    stars: 6840,
    forks: 490,
    openIssues: 392,
    watchers: 136,
    language: "Rust",
    license: "GPL-3.0",
    topics: ["privacy", "security", "vpn", "linux"],
    createdAt: "2017-06-07T00:00:00Z",
    updatedAt: "2026-08-23T16:23:00Z",
    pushedAt: "2026-08-23T14:08:00Z",
    starDelta7d: 113,
    contributorCount: 228,
    isVerified: true,
    homepage: "https://mullvad.net",
    htmlUrl: "https://github.com/mullvad/mullvadvpn-app",
    avatarUrl: "https://github.com/mullvad.png",
  },
  {
    id: 17,
    owner: "seaweedfs",
    name: "seaweedfs",
    fullName: "seaweedfs/seaweedfs",
    description: "A fast distributed storage system for blobs, objects, files, and data lakes.",
    stars: 27640,
    forks: 2480,
    openIssues: 289,
    watchers: 418,
    language: "Go",
    license: "Apache-2.0",
    topics: ["distributed-systems", "storage", "database", "go"],
    createdAt: "2014-07-14T00:00:00Z",
    updatedAt: "2026-08-23T18:54:00Z",
    pushedAt: "2026-08-23T18:50:00Z",
    starDelta7d: 186,
    contributorCount: 392,
    isVerified: true,
    homepage: "https://seaweedfs.com",
    htmlUrl: "https://github.com/seaweedfs/seaweedfs",
    avatarUrl: "https://github.com/seaweedfs.png",
  },
  {
    id: 18,
    owner: "exo-explore",
    name: "exo",
    fullName: "exo-explore/exo",
    description: "Run AI models across a cluster of everyday devices at home.",
    stars: 24850,
    forks: 1810,
    openIssues: 178,
    watchers: 260,
    language: "Python",
    license: "GPL-3.0",
    topics: ["machine-learning", "distributed-systems", "apple-silicon", "python"],
    createdAt: "2024-06-16T00:00:00Z",
    updatedAt: "2026-08-22T21:40:00Z",
    pushedAt: "2026-08-22T20:45:00Z",
    starDelta7d: 524,
    contributorCount: 131,
    isVerified: false,
    htmlUrl: "https://github.com/exo-explore/exo",
    avatarUrl: "https://github.com/exo-explore.png",
  },
];

export interface MockRepositoryQuery {
  query?: string;
  sort?: RepositorySort;
  topic?: string;
  language?: string;
}

export function findMockRepository(
  owner: string,
  name: string,
): Repository | undefined {
  const fullName = `${owner}/${name}`.toLowerCase();
  return mockRepositories.find(
    (repository) => repository.fullName.toLowerCase() === fullName,
  );
}

export function queryMockRepositories({
  query = "",
  sort = "rising",
  topic,
  language,
}: MockRepositoryQuery = {}): Repository[] {
  let repositories = filterRepositories(mockRepositories, query);

  if (topic) {
    repositories = repositories.filter((repository) =>
      repository.topics.includes(topic.toLowerCase()),
    );
  }

  if (language) {
    repositories = repositories.filter(
      (repository) =>
        repository.language.toLowerCase() === language.toLowerCase(),
    );
  }

  return sortRepositories(repositories, sort);
}

export const discoveryTopics = [
  { slug: "developer-tools", label: "Developer tools", count: 1482 },
  { slug: "linux", label: "Linux", count: 926 },
  { slug: "defi", label: "DeFi", count: 604 },
  { slug: "self-hosted", label: "Self-hosted", count: 1186 },
  { slug: "machine-learning", label: "Machine learning", count: 1324 },
  { slug: "terminal", label: "Terminal", count: 718 },
  { slug: "security", label: "Security", count: 842 },
  { slug: "distributed-systems", label: "Distributed systems", count: 512 },
] as const;
